spring:
  application:
    name: pms
  datasource:
    url: jdbc:mysql://localhost:3306/pms
    username: root
    password: pasS@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Use 'update', 'create', 'create-drop', or 'validate' as per your requirement
    show-sql: true  # Enables SQL query logging
